config/routes.rb
Rails.application.routes.draw do

  get 'fields/index'

  get 'fields/import'

  namespace :admin do
       root 'index#index'
       resources :index
       resources :tenants
       resources :landlords
       resources :mpesas
       resources :books
  end

   

  resources :disburses
  resources :houses
  resources :tenants do
    get :search, on: :collection
    get :search_house, on: :collection
  end
  resources :landlords
  resources :properties
  resources :transactions do
    get :search, on: :collection
  end
  resources :fields
  resources :receipts

  devise_for :users, only: :session, path: 'session',
             path_names: { sign_in: 'login', sign_out: 'logout' }
  resources :users, only: [:show]
  resources :assign_house, controller: 'assigns'

  resources :fields do
  collection { post :import }
  end
  root to: 'home#index' 

end  
 

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @transactions = Transaction.all
  end

  def show
   @transaction = Transaction.find(params[:id])
  end

  def new
    tenants = Tenant.all
    @tenants =  tenants.map{|t| [t.full_name, t.id] }
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def search
    @tenant = Tenant.where(id: params[:search]).first
    if @tenant.present?
      @transaction = @tenant.transactions.last
    end
  end

end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/create.html.erb
<h1>Transactions#create</h1>
<p>Find me in app/views/transactions/create.html.erb</p>

app/views/transactions/destroy.html.erb
<h1>Transactions#destroy</h1>
<p>Find me in app/views/transactions/destroy.html.erb</p>

app/views/transactions/edit.html.erb
<h1>Transactions#edit</h1>
<p>Find me in app/views/transactions/edit.html.erb</p>

app/views/transactions/index.html.erb
<table id="transactions" class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Account No.</th>
      <th>Names</th>
      <th>Property</th>
      <th>Unit</th>
      <th>Phone</th>
      <th>Paid</th>
      <th>Date Last paid</th>
      <th>Action</th>
      <th>Click for</th>
    </tr>
  </thead>
  <tbody>
    <% @transactions.each do |t|  %>
      <tr>
        <td><%= t.tenant_id %></td>
        <td><%= t.tenant.full_name  if t.tenant.present? %></td>
        <td><%= t.month %></td>
        <td><%= t.amount %></td>
        <td><%= t.receipt_no %></td>
        <td><%= t.mode %></td>
        <td><%= t.created_at.strftime("%Y-%m-%d") %></td>
        <td><%= link_to 'Show', tenant_path(t), method: :get %></td>
        <td><%= link_to 'Edit', edit_tenant_path(t), method: :get %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<script>
  $(document).ready(function() {
    $('#transactions').dataTable();
  });
</script>
        

app/views/transactions/indexx.html.erb
<%= form_tag import_from_excel_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import", :class=> "btn"%> 
<% end %>

<h1>Field transactions listing</h1>

<div class="table-responsive">
      <table id="landlords" class="table table-striped table-bordered">

  <thead>
    <tr>
   
      <th>Account No</th>
      <th>Property No</th>
      <th>Plot Number</th>
      <th>Unit No</th>
      <th>Amount</th>
      <th>Receipt</th>
      <th>Mode</th>
         
      
        

    </tr>
  </thead>

  <tbody>
    <% @fields.each do |f| %>
      <tr>
       
         <td><%= f.tenant_id %></td>
         <td><%= f.property_id%></td>
        <td><%= f.plot_no %></td>
        <td><%= f.unit_no %></td>
        <td><%= f.amount %></td>
        <td><%= f.receipt %></td>
        <td><%= f.mode %></td>


        
        </td>
      </tr>
    <% end %>
  </div> 
  </tbody>
</table>

app/views/transactions/new.html.erb
<div class="x_content">
  <div class="" role="tabpanel" data-example-id="togglable-tabs">
    <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
      <li role="presentation" class="active"><a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">Office Rent</a></li>
      <li role="presentation" class=""><a href="#tab_content2" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">Field Rent</a></li>
      <li role="presentation" class=""><a href="#tab_content3" role="tab" id="profile-tab2" data-toggle="tab" aria-expanded="false">Receipts & Payments</a></li>
      <li role="presentation" class=""><a href="#tab_content4" role="tab" id="profile-tab3" data-toggle="tab" aria-expanded="false">Ajustments</a></li>
    </ul>
  </div>

  <div id="myTabContent" class="tab-content">
    <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">
      <div class="col-md-6 col-xs-12">

        <div class="input-group">
          <%= form_tag(search_transactions_path, :method => "get", remote: true) do %>
            <%= select_tag :search, options_for_select(@tenants), id: "transaction_search", class: "chosen-select" %>
           <%= submit_tag "Search" %>
          <% end %>
        </div>

        <form class="form-horizontal form-label-left input_mask">
          <div class="form-group">
            <label class="control-label col-md-5 col-sm-5 col-xs-12">Account No.</label>
            <div class="col-md-7 col-sm-7 col-xs-12">
              <input type="text" class="form-control" disabled="disabled" placeholder="Account No." id="trans-account-no">
            </div>
          </div>

          <div class="form-group">
            <label class="control-label col-md-5 col-sm-5 col-xs-12"> Date </label>
            <div class="col-md-7 col-sm-7 col-xs-12">
              <input type="text" class="form-control" disabled="disabled"  placeholder=" Date" id="trans-date">
            </div>
          </div>

          <div class="form-group">
            <label class="control-label col-md-5 col-sm-5 col-xs-12">Full Names </label>
              <div class="col-md-7 col-sm-7 col-xs-12">
                <input type="text" class="form-control"  disabled="disabled" placeholder="full names" id="trans-full-name" >
              </div>
          </div>

          <div class="form-group">
            <label class="control-label col-md-5 col-sm-5 col-xs-12">Plot.</label>
            <div class="col-md-7 col-sm-7 col-xs-12">
              <input type="text" class="form-control" disabled="disabled"  placeholder="plot" id="trans-plot" >
            </div>
          </div>

          <div class="form-group">
            <label class="control-label col-md-5 col-sm-5 col-xs-12">Unit Name:</label>
            <div class="col-md-7 col-sm-7 col-xs-12">
              <input type="text" class="form-control" disabled="disabled"  placeholder="unit" id="trans-unit-name">
            </div>
          </div>

          <div class="form-group">
            <label class="control-label col-md-5 col-sm-5 col-xs-12">Rent Payable:</label>
            <div class="col-md-7 col-sm-7 col-xs-12">
              <input type="text" class="form-control" disabled="disabled"  placeholder="Rent Payable" id="trans-rent-payable" >
            </div>
          </div>

          <div class="form-group">
            <label class="control-label col-md-5 col-sm-5 col-xs-12">Current Month:</label>
            <div class="col-md-7 col-sm-7 col-xs-12">
              <input type="text" class="form-control" disabled="disabled"  placeholder="Current Month" id="trans-current-month" >
            </div>
          </div>

          <div class="form-group">
            <label class="control-label col-md-5 col-sm-5 col-xs-12">Arrears/Over pay: <span class="required">*</span></label>
            <div class="col-md-7 col-sm-7 col-xs-12">
              <input class="date-picker form-control col-md-7 col-xs-12" disabled="disabled" required="required" type="text" id="trans-arrears" >
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-md-5 col-sm-5 col-xs-12">Total:</label>
            <div class="col-md-7 col-sm-7 col-xs-12">
              <input type="text" class="form-control" disabled="disabled"  placeholder="Total" id="trans-total">
            </div>
          </div>

          <div class="form-group">
            <label class="control-label col-md-5 col-sm-5 col-xs-12">Last Payment <span class="required">*</span>
            </label>
            <div class="col-md-7 col-sm-7 col-xs-12">
              <input class="date-picker form-control col-md-7 col-xs-12" disabled="disabled" required="required" type="last payment" id="trans-last-payment" >
            </div>
          </div>

          <div class="form-group">
            <label class="control-label col-md-5 col-sm-5 col-xs-12">Late Fee Penalty <span class="required">*</span>
            </label>
            <div class="col-md-7 col-sm-7 col-xs-12">
              <input class="date-picker form-control col-md-7 col-xs-12" required="required" disabled="disabled" type="last payment date" id="trans-late-fee" >
            </div>
          </div>
          <div class="ln_solid"></div>
        </form>
      </div>

      <div class="col-md-6 col-xs-12">
        <form class="form-horizontal form-label-left input_mask">
          <div class="form-group">
            <label class="control-label col-md-4 col-sm-4 col-xs-12"> Amount </label>
            <div class="col-md-8 col-sm-8 col-xs-12">
              <input type="text" class="form-control"  placeholder="amount">
            </div>
          </div>

          <div class="form-group">
            <label class="control-label col-md-4 col-sm-4 col-xs-12">Select</label>
            <div class="col-md-8 col-sm-8 col-xs-12">
              <select class="form-control">
                <option>Choose option</option>
                <option>Cash</option>
                <option>Cheque</option>
                <option>Mpesa</option>
                <option>LL</option>
              </select>
            </div>
          </div>

          <div class="form-group">
            <label class="control-label col-md-4 col-sm-4 col-xs-12">Cheque No.</label>
            <div class="col-md-8 col-sm-8 col-xs-12">
              <input type="text" class="form-control"  placeholder="Cheque No.">
            </div>
          </div>

          <div class="form-group">
            <label class="control-label col-md-4 col-sm-4 col-xs-12">Mpesa code:</label>
            <div class="col-md-8 col-sm-8 col-xs-12">
              <input type="text" class="form-control"  placeholder="mpesa">
            </div>
          </div>

          <div class="ln_solid"></div>

          <div class="x_title">
             <h4>Tenant charges </h4>
          </div>

          <div class="form-group">
            <label class="control-label col-md-4 col-sm-4 col-xs-12">Select</label>
            <div class="col-md-8 col-sm-8 col-xs-12">
              <select class="form-control">
                <option>Choose Account</option>
                <option>Late Fees</option>
                <option>Cheque</option>
                <option>Unlock</option>
                <option>Pledge Extension</option>
                <option>Storage</option>
                <option>Transport</option>
                <option>Padlock</option>
                <option>Watchman</option>
                <option>Water</option>
                <option>Electricity</option>
              </select>
            </div>
          </div>

          <div class="form-group">
            <label class="control-label col-md-4 col-sm-4 col-xs-12">Select</label>
            <div class="col-md-8 col-sm-8 col-xs-12">
              <select class="form-control">
                <option>Choose Pay Mode</option>
                <option>Cash</option>
                <option>Cheque</option>
                <option>Mpesa</option>
                <option>LL</option>
              </select>
            </div>
          </div>

				  <div class="form-group">
            <label class="control-label col-md-4 col-sm-4 col-xs-12">Amount:</label>
            <div class="col-md-8 col-sm-8 col-xs-12">
              <input type="text" class="form-control"  placeholder="amount">
            </div>
          </div>

          <div class="form-group">
            <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
              <button type="button" class="btn btn-primary">Cancel</button>
              <button type="submit" class="btn btn-success">Submit</button>
            </div>
          </div>

          <div class="form-group">
            <label class="control-label col-md-4 col-sm-4 col-xs-12">Narration:</label>
            <div class="col-md-8 col-sm-8 col-xs-12">
              <input type="text" class="form-control"  placeholder="narration">
            </div>
          </div>
        </form>
      </div>
    </div>

    <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="profile-tab">
      <table id="datatable-buttons" class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>Tenant No./Unit Name</th>
            <th>Property</th>
            <th>Amount Paid</th>
            <th>Account</th>
            <th>Arrears</th>
            <th>Mode</th>
            <th>Receipt</th>
          </tr>
        </thead>
        <tbody>
        </tbody>
      </table>
    </div>

    <div role="tabpanel" class="tab-pane fade" id="tab_content3" aria-labelledby="profile-tab">
      <div class="x_content">
        <div class="panel-body">
          <div class="row">
            <div class="col-lg-12">
              <form role="form">
                <div class="col-lg-3">
                  <div class="form-group">
                    <label>Unit Name</label>
                    <input class="form-control" placeholder="Unit name">
                  </div>
                </div>

                <div class="col-lg-3">
                  <div class="form-group">
                    <label>Type</label>
                    <label>Tenant Name</label>
                    <select class="form-control">
                      <option>John</option>
                      <option>Mary</option>
                      <option>Jed</option>
                      <option>Mark</option>
                      <option>Eety</option>
                      <option>Eunice</option>
                    </select>
                  </div>
                </div>

                <div class="col-lg-3">
                  <div class="form-group">
                    <label>Rent Payable</label>
                    <input class="form-control" placeholder="Rent Payable">
                  </div>
                </div>

                <div class="col-lg-3">
                  <div class="form-group">
                    <label>Amount</label>
                    <input class="form-control" placeholder="Amount">
                  </div>
                </div>
                <button type="submit" class="btn btn-default">Add Rent</button>
              </form>
            </div>
          </div>
        </div>
        <div role="tabpanel" class="tab-pane fade" id="tab_content4" aria-labelledby="profile-tab">
          <p>Rent, charges Reversal, cancellation, </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/transactions/search.js.erb
<% if @transaction.present? %>
  #$("#trans-account-no").val("<%= @tenant.id %>");
  $("#trans-date").val("<%= @transaction.date %>");
  $("#trans-full-name").val("<%= @tenant.full_name %>");
  $("#trans-plot").val("<%= @transaction.property.plot_no if (@transaction.property.present?) %>");
  $("#trans-unit-name").val("<%= @tenant.assigns.first.unit_name if (@tenant.assigns.present?) %>");
  $("#trans-rent-payable").val("<%= @tenant.houses.order(:id).last.rent_payable if @tenant.houses.present? %>");
  $("#trans-current-month").val("<%= @transaction.month %>");
  $("#trans-arrears").val("<%= @tenant.arrears.last.amount if @tenant.arrears.last %>");
  $("#trans-total").val("<%= @transaction.amount %>");
  $("#trans-last-payment").val("<%= @transaction.date %>");
  $("#trans-late-fee").val("<%= (@transaction.amount.to_f * 0.10) if (@transaction.date.strftime("%d").to_i > 12 ) %>");
<% else %>
  $("#trans-account-no, #trans-date, #trans-full-name, #trans-plot, #trans-unit-name, #trans-rent-payable, #trans-current-month, #trans-arrears, #trans-total, #trans-last-payment, #trans-late-fee").val("");
<% end %>

app/views/transactions/show.html.erb
<h1>Transactions#show</h1>
<p>Find me in app/views/transactions/show.html.erb</p>

app/views/transactions/update.html.erb
<h1>Transactions#update</h1>
<p>Find me in app/views/transactions/update.html.erb</p>